version: "3.9"
services:
  demo:
    image: jettydemo:0.0.1-SNAPSHOT
    environment:
    - SERVER_PORT=8080
    - USE_SSL=false
    - USE_LOGSTASH=false
    - APP_LOGGING_LEVEL=info
    ports:
    - "8080:8080"

